# Generated by Django 5.1 on 2024-08-29 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_cart_user_cart_product_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('session_key', 'product')},
        ),
    ]
